name: UltraFly
version: 1.0.0
api: [5.0.0]
main: aqua\UltraFly\Main
author: aqua
description: A plugin to enable and disable flying with permission check.
commands:
  fly:
    description: Toggle flying
    permission: UltraFly.cmd
permissions:
  UltraFly.cmd:
    description: "Allows the user to toggle fly."
    default: true
